<?php

namespace Tests\Unit\Http\Requests;

use Tests\TestCase;

/**
 * @see \App\Http\Requests\StoreStoreRequest
 */
class StoreStoreRequestTest extends TestCase
{
    /** @var \App\Http\Requests\StoreStoreRequest */
    private $subject;

    protected function setUp() : void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\StoreStoreRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'name' => [
                'required',
                'unique:stores,name',
            ],
        ], $actual);
    }

    // test cases...
}
