<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AdminPanelController
 */
class AdminPanelControllerTest extends TestCase
{
    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin-panel.edit'));

        $response->assertRedirect(route('stores.index'));

        // TODO: perform additional assertions
    }

    // test cases...
}
